# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI on Tag created

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Use tag
      run: echo ${{steps.tag.outputs.tag}}
