# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI on Tag created

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    #steps:
    #- name: Get tag
    #  id: tag
    #  uses: dawidd6/action-get-tag@v1
    #- name: Use tag
    #  run: echo ${{steps.tag.outputs.tag}}
    steps:      
      - uses: olegtarasov/get-tag@v2.1        
        name: Get tag name
        id: tagName
        with:
          tagRegex: "^(v | V)*"           
          
      #- name: Some other step # Output usage example
      #  uses: olegtarasov/get-tag@v2.1        
      #  with:
      #    dirname: ${{ steps.tagName.outputs.package }}
      #    tagname: ${{ steps.tagName.outputs.version }}          
      - name: Something to do
        run: echo $GIT_TAG_NAME; 
        # echo ${{ steps.tagName.outputs.package }}; echo ${{ steps.tagName.outputs.version }}
      

