# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI on Tag created

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:      
      - name: Filter Tag Name
        uses: olegtarasov/get-tag@v2.1        
        id: tagName
        with:
           tagRegex: "(\\d.*\\d)"

      - name: Something to do
        run: echo $GIT_TAG_NAME;         
      

